### PR TITLE
Drop support for java jdk1.6 and fix #122

### LINKED ISSUE #122: naming conflicts
The default property names that the plugin creates cannot be placed into a JSON structure. For example, these two values cannot be put into a JSON object commit.id

commit.id:2eed44f166489b2f03169a2e2d7f910430ecf7a9
commit.id.abbrev:2eed44f

Instead, the first value should be named as a field in the "commit.id" object. Foe example:

commit.id.full:2eed44f166489b2f03169a2e2d7f910430ecf7a9
commit.id.abbrev:2eed44f

### PR DESCRIPTION
**Pull request by TheSnoozer**

### CODE REVIEW

**Comment by ktoso** [comment]
Yay, let's also add this to README.md and I'll cut a release

**Comment by TheSnoozer** [comment]
another PR is currently in preparation ;)

**Comment by ktoso** [comment]
Awesome, I'll be back to cut the release soon - bicicling and meetup now :)

-- 
Konrad 'ktoso’ Malawski
Akka @ Typesafe
java.pl / geecon.org / krakowscala.pl / lambdakrk.pl

On 18 June 2015 at 19:04:44, TheSnoozer (notifications@github.com) wrote:

another PR is currently in preparation ;)

**Comment by TheSnoozer** [comment]
sounds like fun :)
I merge everything that's green :)

**Comment by TheSnoozer** [comment]
I'll merge it :-)

**Pull request merged**
