### PR TITLE
Use `git ls-remote --get-url` to get the remote url

### PR DESCRIPTION
**Pull request by Shredder121**
Implementation detail and GOTCHA:
This also follows remote tracking branches, so if the name of the remote is different, then that is used.
image

I am usually on `origin`, but on other projects (like these) I am on `upstream`(since I can't push).
This means that the plugin doesn't fail when not used with `origin`.

Is this desired behavior?
If not, I can make it use `git ls-remote --get-url origin` instead.

Anyway, it does away with the parsing of porcelain output.
Let me know what you think.

### CODE REVIEW

**Comment by Shredder121** [comment]
That was my second question, could someone test this? :sweat_smile:

**Comment by Shredder121** [comment]
I'll see if I can also test it, using Windows here.

**Comment by Shredder121** [comment]
So.
I can now guarantee that the input of `stripCredentialsFromOriginUrl` isn't null.
Do you want me to annotate that?

**Comment by ktoso** [comment]
Yes please, the project tries to be consistent with use of those markers

**Comment by Shredder121** [comment]
Hmm.. actually, only the `NativeGitProvider` now provides  nonnull.
The `JGitProvider` still provides nulls.

**Comment by ktoso** [comment]
Good improvement as far as I can see, thanks!

**Comment by Shredder121** [comment]
Nice, thank you!

**Pull request merged**
