### PR TITLE
Modularize v3

### PR DESCRIPTION
**Pull request by TheSnoozer**
I know we tried this before...just thinking to bring this back alive ;P

tried to use the existing branch but it seems to be easier just to redo it since a lot of stuff has changed over time...

### CODE REVIEW

**Comment by TheSnoozer** [comment]
@ktoso could you review this PR? :-)

**Comment by ktoso** [comment]
On it!

**Comment by TheSnoozer** [comment]
I'll dump that and prepare a commit that updates modularization-effort

**Comment by ktoso** [comment]
Okey, sorry I did not complete review; traveling kills all such efforts with random interruptions :<

**Comment by ktoso** [comment]
It still would be very interesting!

**Comment by TheSnoozer** [comment]
Don't worry all good :-)

**Pull request closed without merging**
