### PR TITLE
update jgit from 3.7.0.201502260915-r to 4.0.0.201506090130-r

### PR DESCRIPTION
**Pull request by Martin-Wegner**
update jgit from 3.7.0.201502260915-r to 4.0.0.201506090130-r to fix issue #203

### CODE REVIEW

**Comment by Martin-Wegner** [comment]
jgit 4.0.0.201506090130-r needs Java 7 for AutoCloseable...

**Comment by ktoso** [comment]
Sounds like we should kill 6 finally, I'm ok with that. // cc @TheSnoozer

**Comment by TheSnoozer** [comment]
I would say kill jdk1.6.
However, I would say if we kill the jdk1.6 we need to deploy a major version (2.2.0) and finally fix #122 as well.

**Comment by ktoso** [comment]
Sounds like plan to me!

-- 
Konrad 'ktoso’ Malawski
Akka @ Typesafe
java.pl / geecon.org / krakowscala.pl / lambdakrk.pl

On 18 June 2015 at 18:45:44, TheSnoozer (notifications@github.com) wrote:

I would say kill jdk1.6.
However, I would say if we kill the jdk1.6 we need to deploy a major version (2.2.0) and finally fix #122 as well.

**Comment by TheSnoozer** [comment]
just moved all tickets with milestone 2.1.16 to 2.2.0; I think it's safe to merge this (travis is green on jdk1.8 and jdk1.7) & I'll kill the jdk1.6 afterwards

**Comment by TheSnoozer** [comment]
Thanks @Martin-Wegner for your PR and performing the test's on this issue :-)

**Pull request merged**
