### PR TITLE
Closest tag function return incorrect value. Fixed comparator

### PR DESCRIPTION
**Pull request by AlehGalo**
The issue is related to the closes tag.

For example we have tags like
1(01.01.2015)             2(10.01.2015)     3(20.01.2015)                      4(30.01.2015)

when specify option in maven plugin vcs.closest.tag.name it return the first 1 but I expect to the 4 instead of 1.

Could you please review the fix or let me know if I am wrong.

Thanks in advance.

### CODE REVIEW

**Comment by ktoso** [comment]
Are you sure about this change?
It breaks tests of this exact feature:

```
[0] false (shouldGenerateClosestTagInformationWhenCommitHasTwoTags)(pl.project13.maven.git.GitCommitIdMojoIntegrationTest)  Time elapsed: 0.041 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<'[newes]t-tag'> but was:<'[lightweigh]t-tag'>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

Please run tests before submitting a PR :)
I seem to remember `newest-tag` is indeed the newest one... Can we make sure this change is needed?

**Comment by TheSnoozer** [comment]
The closes tag also depends on the branch you are currently on.
e.g. you create a tag 1(01.01.2015) on branch master
and create the tags 2(10.01.2015) 3(20.01.2015) 4(30.01.2015) on branch FbNewFeature and would like to know the closest tag on branch master you'll get 1(01.01.2015).
I you merge the FbNewFeature into the master you'll get 4(30.01.2015).

Check this with git describe --long.

**Comment by AlehGalo** [comment]
Thank you for the fast reponse and sorry for not running tests first. 
I will investigate more and let you all know.

**Comment by ktoso** [comment]
Thanks!

**Comment by TheSnoozer** [comment]
Closed & not merged.

**Pull request closed without merging**
