### PR TITLE
Fix for #234 & #236

### PR DESCRIPTION
**Pull request by TheSnoozer**

### CODE REVIEW

**Comment by ktoso** [comment]
Resolves #234 
Resolves #236

**Comment by ktoso** [comment]
Great fixes, thanks!

**Comment by ktoso** [comment]
I'll roll a release soon

**Comment by TheSnoozer** [comment]
I'll have some time the next upcoming days. I'll check the other issues as well ;-)

**Comment by ktoso** [comment]
Thats great, thank you!

**Pull request merged**
