### PR TITLE
Update JUnitParams to 1.0.4

### PR DESCRIPTION
**Pull request by mkordas**

### CODE REVIEW

**Comment by ktoso** [comment]
Travis said "no cigar", can you please verify that change>

**Comment by TheSnoozer** [comment]
Cumputer also says:
```
pl.project13.maven.git.GitCommitIdMojoIntegrationTest Time elapsed: 0.045 sec <<< ERROR!

java.lang.NoSuchMethodError: org.junit.runner.Description.createTestDescription(Ljava/lang/String;Ljava/lang/String;Ljava/io/Serializable;)Lorg/junit/runner/Description;
at junitparams.internal.TestMethod.describe(TestMethod.java:106)
at junitparams.internal.ParameterisedTestClassRunner.describeParameterisedMethod(ParameterisedTestClassRunner.java:162)
at junitparams.JUnitParamsRunner.describeMethod(JUnitParamsRunner.java:460)
at junitparams.internal.ParametrizedTestMethodsFilter.filteredMethods(ParametrizedTestMethodsFilter.java:30)
at junitparams.JUnitParamsRunner.getListOfMethods(JUnitParamsRunner.java:456)
at junitparams.JUnitParamsRunner.getDescription(JUnitParamsRunner.java:445)
at org.junit.runners.ParentRunner.run(ParentRunner.java:296)
at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by mkordas** [comment]
Build fixed, it was enough to rebase the commit.

**Comment by ktoso** [comment]
thanks

**Pull request merged**
